MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
  # WEIGHT: "tools/logs/last_checkpoint"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  # DETECT_CLASSES: ("Car",)
  TRAIN: ("kitti_train",)
  TEST: ("kitti_test",)
  TRAIN_SPLIT: "trainval"
  TEST_SPLIT: "test"
SOLVER:
  BASE_LR: 2.5e-4
  STEPS: (1000, 2000, 3000, 4000, 5000)
  MAX_ITERATION: 6000
  IMS_PER_BATCH: 24